services:
  laravel_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:8000"
      - "8080:8080"
      - "5173:5173"
  db:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # !!! CAMBIA QUESTO !!!
      MYSQL_DATABASE: laravel
      MYSQL_USER: siakoo
      MYSQL_PASSWORD: root # !!! CAMBIA QUESTO !!!
    ports:
      - "3306:3306"
    volumes:
      # 'db_data' è un volume gestito da Docker per persistere i dati
      # '/var/lib/mysql' è la directory dove MySQL salva i dati nel container
      - db_data:/var/lib/mysql

volumes:
  db_data:
